### ISSUE TITLE
operator status Progressing=True long after the cluster reaches idle

### ISSUE THREAD

**Issue by sjenning** [openshift/cluster-samples-operator#100]
I observe the operator stay in `Progressing=True` for 6-8m after the last pod in the cluster (typically telemeter-client) is `Running`.  The installers waits on all operators to be `Progressing=False` before reporting completion.  Happened on 2 of 3 install runs for me.

**Comment by gabemontero** [comment]
Bad registry download performance *could* lead to that @sjenning 

Per https://github.com/openshift/cluster-samples-operator#troubleshooting
running `oc get configs.samples.operator.openshift.io instance -o yaml` would be helpful.

@bparees perhaps the first signs of the ramifications of our switch to rhel and adding the samples operator 's stub cluster status obj into the loop

**Comment by sjenning** [comment]
I'll try to recreate and get this data

**Comment by gabemontero** [comment]
thanks @sjenning

**Comment by bparees** [comment]
There is on-going discussion about what the installer should be waiting for.  Last time I brought this up I was told it was waiting for available=true (no mention of progressing=false), so we updated this operator to change what "available" means so it can claim to be available sooner.  I'm not inclined to do the same with progressing..  the operator is progressing because it is importing the samples it is supposed to import.  Changing that behavior just makes the status reporting less useful.

And there's a new condition ("upgradeable") being proposed that it should be waiting for instead of any of those things.

So before we go making changes to the samples operator to work around this (the only option for us would be to lie about progressing status, which makes our status useless), can we finalize a rule about what the CVO should actually be waiting for so that operators which have lengthy startup processes have a way to not block the install but also not lie about their status?

/cc @deads2k @abhinavdahiya

**Comment by gabemontero** [comment]
I may be seeing this in PR testing from https://github.com/openshift/cluster-samples-operator/pull/99 ... investigating the latest run

**Comment by gabemontero** [comment]
In my PR https://github.com/openshift/cluster-samples-operator/pull/99, it is hitting the manifest ordering issue getting fixed with https://github.com/openshift/cluster-samples-operator/pull/101

I'll have to pick the 101 fix into the 99 PR.

That bug though would always cause an error.  If @sjenning at least had some success, we are back to perf and @bparees 's points / questions at https://github.com/openshift/cluster-samples-operator/issues/100#issuecomment-462824850

@sjenning - it does not make sense for you to try reproduce until https://github.com/openshift/cluster-samples-operator/pull/101 merges minimally ... it might be a good data point for @bparees 's questions to have the debug when you see an *intermittent* failure

**Comment by gabemontero** [comment]
https://github.com/openshift/cluster-samples-operator/pull/101 has merged

I'll post here again once I get the buildsys email

**Comment by bparees** [comment]
answer to my question above:
https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#how-clusterversionoperator-handles-clusteroperator-in-release-image

however i still believe this is changing w/ the upgradeable condition that's being added, so i still don't think we should make any changes in this behavior right now.

**Comment by gabemontero** [comment]
OK I was finally able to bring up an AWS cluster using today's latest installer (after hitting some of the known flakes discussed in 4-dev-triage)

Times:
- image imports:  8 minutes 39 seconds

start:
```
time="2019-02-13T16:14:01Z" level=info msg="CRDUPDATE progressing true update"
```

end:
```
time="2019-02-13T16:22:40Z" level=info msg="The samples are now at version 4.0.0-alpha1-0f6d29624"
```

- sample api obj creation

we actually got some connections refused from the master on objecct creation, like 

```
time="2019-02-13T16:12:36Z" level=error msg="unable to sync: Get https://172.30.0.1:443/apis/template.openshift.io/v1/namespaces/openshift/templates/jws31-tomcat7-mongodb-s2i: dial tcp 172.30.0.1:443: connect: connection refused, requeuing"

```
time="2019-02-13T16:12:09Z" level=info msg="Spec is valid because this operator has not processed a config yet"
time="2019-02-13T16:12:09Z" level=info msg="processing subdir 3scale from dir /opt/openshift/operator/ocp-x86_64"

so some retries had to occur.....based on that, I wonder if making api obj creation multi-threaded will just lead to more connection refusals by the master and more retries anyway.

ultimately it took 3 minutes 10 seconds after retries via controller requeue:

start:
```
time="2019-02-13T16:12:09Z" level=info msg="Spec is valid because this operator has not processed a config yet"
time="2019-02-13T16:12:09Z" level=info msg="processing subdir 3scale from dir /opt/openshift/operator/ocp-x86_64"
```

end: 
```
time="2019-02-13T16:15:19Z" level=info msg="CRDUPDATE exist true update"
```

- reading in of imagestream/template json files ... within a second

- overall

there is some overlap between creation of samples and imagestreams finishing import (as we create the streams first and let them get started importing images while we are creating templates)

for this run, start to finish was 10 minutes 34 seconds.

**Comment by gabemontero** [comment]
@sjenning with the latest install from today it has the RBAC fixes we noted yesterday

Please do that repro when time permits for you.

And if possible I'd like to add:

```
`oc logs -f `oc get pods -o name -n openshift-cluster-samples-operator`
```

To the 
`oc get configs.samples.operator.openshift.io instance -o yaml`

I noted before.

I'll be circling back and doing some additional installs to gather more comparison points to what I saw in https://github.com/openshift/cluster-samples-operator/issues/100#issuecomment-463302166

**Comment by gabemontero** [comment]
As a point of comparison, after my cluster had been up for a few hours, I nuked the samples, samples operator config / cluster status and brought the deployment down.

- Total end to end creation time: **1 Minute 23 Seconds**
start:
```
time="2019-02-13T19:54:11Z" level=info msg="Go Version: go1.10.3"
time="2019-02-13T19:54:11Z" level=info msg="Go OS/Arch: linux/amd64"
time="2019-02-13T19:54:11Z" level=info msg="template client &v1.TemplateV1Client{restClient:(*rest.RESTClient)(0xc4203de180)}"
time="2019-02-13T19:54:11Z" level=info msg="image client &v1.ImageV1Client{restClient:(*rest.RESTClient)(0xc4203de240)}"
time="2019-02-13T19:54:11Z" level=info msg="Copying secret coreos-pull-secret from the kube-system namespace into the operator's namespace"
time="2019-02-13T19:54:11Z" level=info msg="creating default Config"
time="2019-02-13T19:54:14Z" level=info msg="waiting for informer caches to sync"
time="2019-02-13T19:54:14Z" level=info msg="started events processor"
time="2019-02-13T19:54:14Z" level=info msg="management state set to managed"
time="2019-02-13T19:54:14Z" level=info msg="Spec is valid because this operator has not processed a config yet"
time="2019-02-13T19:54:14Z" level=info msg="processing subdir 3scale from dir /opt/openshift/operator/ocp-x86_64"
```


end:
```
time="2019-02-13T19:55:34Z" level=info msg="The samples are now at version 4.0.0-alpha1-0f6d29624"
```

- image import:  started while the creations were going on, but completed **9 seconds** after the last sample was created

```
time="2019-02-13T19:55:25Z" level=info msg="CRDUPDATE progressing true update"

```

So resource constraint from the other operators during the install bringup is playing **AT LEAST SOME** factor.

**Comment by sjenning** [comment]
didn't catch it in the act because i got distracted but...
```
$ oc get clusteroperators openshift-samples -oyaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  creationTimestamp: 2019-02-13T20:10:15Z <---
  generation: 1
  name: openshift-samples
  resourceVersion: "22311"
  selfLink: /apis/config.openshift.io/v1/clusteroperators/openshift-samples
  uid: 604ae719-2fcb-11e9-82b4-06e40b30205e
spec: {}
status:
  conditions:
  - lastTransitionTime: 2019-02-13T20:22:15Z
    message: Samples installation successful at 4.0.0-alpha1-0f6d29624
    status: "True"
    type: Available
  - lastTransitionTime: 2019-02-13T20:22:18Z  <---
    message: Samples installation successful at 4.0.0-alpha1-0f6d29624
    status: "False"
    type: Progressing
  - lastTransitionTime: 2019-02-13T20:22:18Z
    status: "False"
    type: Failing
  extension: null
  relatedObjects: null
  versions:
  - name: operator
    version: 4.0.0-alpha1-0f6d29624
```
delta of 12m between operator creation and `Progressing` transitioning to `False`.

operator logs
```
time="2019-02-13T20:11:59Z" level=info msg="caching imagestream event dotnet-runtime because we have not yet completed all the samples upserts"
time="2019-02-13T20:11:59Z" level=info msg="updated imagestream dotnet"
time="2019-02-13T20:11:59Z" level=info msg="imagestream create error: the server could not find the requested resource (post imagestreams.image.openshift.io)"
time="2019-02-13T20:11:59Z" level=info msg="error creating samples: the server could not find the requested resource (post imagestreams.image.openshift.io)"
time="2019-02-13T20:11:59Z" level=info msg="CRDUPDATE setting in progress to unknown"
E0213 20:11:59.915013       1 reflector.go:251] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to watch *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
E0213 20:12:00.941388       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:00Z" level=info msg="caching imagestream event jboss-eap72-openshift because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:00Z" level=info msg="caching imagestream event eap-cd-openshift because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:01Z" level=info msg="caching imagestream event fuse7-karaf-openshift because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:01Z" level=info msg="caching imagestream event jboss-fuse70-eap-openshift because we have not yet completed all the samples upserts"
E0213 20:12:01.944640       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:02Z" level=info msg="caching imagestream event jboss-eap64-openshift because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:02Z" level=error msg="unable to sync: the server could not find the requested resource (post imagestreams.image.openshift.io), requeuing"
E0213 20:12:02.962969       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:02Z" level=info msg="Spec is valid because this operator has not processed a config yet"
time="2019-02-13T20:12:02Z" level=info msg="processing subdir 3scale from dir /opt/openshift/operator/ocp-x86_64"

...

time="2019-02-13T20:12:03Z" level=info msg="processing file jws31-tomcat8-postgresql-persistent-s2i.json from dir /opt/openshift/operator/ocp-x86_64/webserver/templates"
time="2019-02-13T20:12:03Z" level=info msg="imagestream create error: the server could not find the requested resource (post imagestreams.image.openshift.io)"
time="2019-02-13T20:12:03Z" level=info msg="error creating samples: the server could not find the requested resource (post imagestreams.image.openshift.io)"
time="2019-02-13T20:12:03Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:12:03Z" level=error msg="unable to sync: retry secret event because in the middle of an sample upsert cycle, requeuing"
E0213 20:12:03.965704       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:03Z" level=info msg="caching imagestream event fuse-apicurito-generator because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:03Z" level=error msg="unable to sync: retry secret event because in the middle of an sample upsert cycle, requeuing"
time="2019-02-13T20:12:04Z" level=info msg="caching imagestream event redhat-openjdk18-openshift because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:04Z" level=info msg="caching imagestream event jboss-processserver64-openshift because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:04Z" level=info msg="caching imagestream event jboss-datagrid65-client-openshift because we have not yet completed all the samples upserts"
E0213 20:12:04.970161       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:05Z" level=info msg="caching imagestream event jboss-datagrid65-openshift because we have not yet completed all the samples upserts"
E0213 20:12:05.972854       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:06Z" level=error msg="unable to sync: the server could not find the requested resource (post imagestreams.image.openshift.io), requeuing"
time="2019-02-13T20:12:06Z" level=info msg="Spec is valid because this operator has not processed a config yet"
time="2019-02-13T20:12:06Z" level=info msg="processing subdir 3scale from dir /opt/openshift/operator/ocp-x86_64"

...

time="2019-02-13T20:12:06Z" level=info msg="processing file jws31-tomcat8-postgresql-persistent-s2i.json from dir /opt/openshift/operator/ocp-x86_64/webserver/templates"
time="2019-02-13T20:12:06Z" level=info msg="imagestream create error: the server could not find the requested resource (post imagestreams.image.openshift.io)"
time="2019-02-13T20:12:06Z" level=info msg="error creating samples: the server could not find the requested resource (post imagestreams.image.openshift.io)"
time="2019-02-13T20:12:06Z" level=info msg="CRDUPDATE setting in progress to unknown"
E0213 20:12:06.975438       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:06Z" level=info msg="caching imagestream event mysql because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:07Z" level=info msg="caching imagestream event jboss-amq-62 because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:07Z" level=info msg="caching imagestream event java because we have not yet completed all the samples upserts"
time="2019-02-13T20:12:07Z" level=info msg="caching imagestream event rhpam72-smartrouter-openshift because we have not yet completed all the samples upserts"
E0213 20:12:07.977818       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:08Z" level=info msg="caching imagestream event jboss-webserver30-tomcat7-openshift because we have not yet completed all the samples upserts"
E0213 20:12:08.980209       1 reflector.go:134] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: Failed to list *v1.ImageStream: the server could not find the requested resource (get imagestreams.image.openshift.io)
time="2019-02-13T20:12:09Z" level=error msg="unable to sync: the server could not find the requested resource (post imagestreams.image.openshift.io), requeuing"
time="2019-02-13T20:12:09Z" level=info msg="Spec is valid because this operator has not processed a config yet"
time="2019-02-13T20:12:09Z" level=info msg="processing subdir 3scale from dir /opt/openshift/operator/ocp-x86_64"

...

time="2019-02-13T20:14:47Z" level=info msg="CRDUPDATE progressing true update"
time="2019-02-13T20:14:50Z" level=error msg="unable to sync: Operation cannot be fulfilled on configs.samples.operator.openshift.io \"instance\": the object has been modified; please apply your changes to the latest version and try again, requeuing"
time="2019-02-13T20:14:50Z" level=info msg="CRDUPDATE exist true update"
time="2019-02-13T20:14:53Z" level=info msg="CRDUPDATE exist true update"
time="2019-02-13T20:14:56Z" level=error msg="unable to sync: Operation cannot be fulfilled on configs.samples.operator.openshift.io \"instance\": the object has been modified; please apply your changes to the latest version and try again, requeuing"
time="2019-02-13T20:15:09Z" level=error msg="unable to sync: retry secret event because in the middle of an sample upsert cycle, requeuing"
time="2019-02-13T20:15:09Z" level=error msg="unable to sync: retry secret event because in the middle of an sample upsert cycle, requeuing"
time="2019-02-13T20:15:12Z" level=info msg="watch event cli not part of operators inventory"
time="2019-02-13T20:15:12Z" level=info msg="watch event installer not part of operators inventory"
time="2019-02-13T20:15:13Z" level=info msg="watch event tests not part of operators inventory"
time="2019-02-13T20:20:39Z" level=error msg="unable to sync: retry secret event because in the middle of an sample upsert cycle, requeuing"
time="2019-02-13T20:20:39Z" level=error msg="unable to sync: retry secret event because in the middle of an sample upsert cycle, requeuing"
time="2019-02-13T20:22:01Z" level=info msg="have not received an upsert event for fuse7-eap-openshift in 5 minutes so cache is skipping this one"
```

**Comment by sjenning** [comment]
grepping for CRD
```
$ oc logs cluster-samples-operator-7dd966d89d-gm28v | grep CRD
time="2019-02-13T20:10:57Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:11:34Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:11:59Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:12:03Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:12:06Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:12:09Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:12:12Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:12:15Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:12:19Z" level=info msg="CRDUPDATE setting in progress to unknown"
time="2019-02-13T20:13:33Z" level=info msg="CRDUPDATE progressing true update"
time="2019-02-13T20:14:47Z" level=info msg="CRDUPDATE progressing true update"
time="2019-02-13T20:14:50Z" level=info msg="CRDUPDATE exist true update"
time="2019-02-13T20:14:53Z" level=info msg="CRDUPDATE exist true update"
time="2019-02-13T20:22:11Z" level=info msg="CRDUPDATE setting in progress to false after examining cached imagestream events"
time="2019-02-13T20:22:15Z" level=info msg="CRDUPDATE upd status version"
time="2019-02-13T20:31:38Z" level=info msg="CRDUPDATE switching import cred to true following openshift namespace event"
time="2019-02-13T20:31:38Z" level=info msg="CRDUPDATE event secret update"
```

**Comment by gabemontero** [comment]
yep not too dissimilar a result from mine on the initial install

I bet if you tried it again once the cluster stabilized, you'd see something along the 10 to 1 reduction I saw

**Comment by sjenning** [comment]
so this is due to the openshift api dropping causing `he server could not find the requested resource (get imagestreams.image.openshift.io)`?

**Comment by gabemontero** [comment]
The easy version to redo after the clusters has installed and stabilized:
- `oc delete config.samples.operator.openshift.io instance `

The operator will recreate after deleting everything

**Comment by gabemontero** [comment]
I would presume so re: your dropping question @sjenning , along with `the server could not find the requested resource (post imagestreams.image.openshift.io)"`

**Comment by bparees** [comment]
if the openshift apiserver is restarting during samples import, that would definitely delay the import process.  And it probably is restarting, at a minimum it's going to restart when the registry operator publishes the internal registry hostname to the apiserver for example, and since both the registry+samples operators start at the same time....

likely other things are triggering apiserver restarts too.  @sjenning i think you had a nice chart that might shed light on that.

**Comment by gabemontero** [comment]
re: apiserver restart / resource constraint, perhaps motivation for making turning on samples a day 2 operation like @bparees and I discussed with @derekwaynecarr at RAL snack time today

**Comment by bparees** [comment]
It feels like a false economy to claim "yeah, the install is faster now" but in reality we've just pushed work off to an admin that has to be done later and which now requires explicit manual steps instead of being automatic.

As a user, i'd rather wait 10 extra minutes up front than have go take some manual action later (which requires that i know i need to do it and know how to do it).  Obviously it's a slippery slope and i understand the motivation for fast installs, but i think we also want maximally functional installs.

**Comment by bparees** [comment]
I'll reiterate that imho the real issue here is that the installer shouldn't block on the samples operator.  We have two ways to fix that:

1) have the samples operator lie/take a different approach about what "available=true/progressing=false" means
2) have the CVO take a different approach about what conditions it expects to see before considering the operator "done".

and of course to that end i prefer (2).

**Comment by sjenning** [comment]
(1) would be faster to implement though.

There is something in that last runlevel of the CVO that causing a redeployment of the controller plane (kube-{apiserver|controller-manager|scheduler} and openshift-{apiserver|controller-manager}.  Probably worth figuring out what is doing that.

**Comment by gabemontero** [comment]
Some cross referencing:  https://github.com/openshift/cluster-image-registry-operator/pull/204 is targeted at reducing the churn caused by the openshift api server having to restart when the image registry propagates its hostname to it.

With the above change, the image reg operator won't report available until it can confirm the openshift api server has consumed the hostname setting.

This could minimally serve as a building block for the sample operator not trying to construct imagestreams and templates until the openshift api server is "stable" for the given startup.

**Comment by gabemontero** [comment]
Some more cross referencing, with https://github.com/openshift/api/pull/206 merging, as consumption of it proliferates, we'll see if use of that condition can help at all in this space.

**Comment by gabemontero** [comment]
And first update on sampling for today;  bringing up my daily dev cluster with the last installer this AM, I saw *NO* churn wrt to api server restart, and the samples operator completed in 1 minute 23 seconds  ... i.e. a duration on par with my samples noted above when I redid the process after startup had completed.

Not sure yet if this is blind luck, or something underneath us has changed to mitigate the api server restart.

I'll be looking into the PR runs today and see if I see similar data.

**Comment by bparees** [comment]
> This could minimally serve as a building block for the sample operator not trying to construct imagestreams and templates until the openshift api server is "stable" for the given startup.

I think there's a difference between what that PR does (treat the imagestream dockerRepositoryStatus as being "part of the imageregistry - if it's not set, the registry isn't available") and adding pre-req conditions to the samples operator.

And i'm against adding pre-req conditions...  there's going to be an expectation that more and more things can attempt to start in parallel and should just reconcile.

More fundamentally...  is there actually a difference in time between:

1) create imagestreams while api server is bouncing, they don't get imported until the apiserver stops bouncing

and

2) wait for the api server to stop bouncing, then create the imagestreams

?

ie are we actually paying any time-cost by creating them while the apiserver is "unstable"?

(we're also unlikey to ever be able to establish when the apiserver is stable..another operator can come along and introduce a restart at any point)

> Not sure yet if this is blind luck, or something underneath us has changed to mitigate the api server restart.

I believe there were some other fixes that went into the apiserver that likely stabilized it a bit.

**Comment by gabemontero** [comment]
On Mon, Feb 18, 2019 at 11:59 AM Ben Parees <notifications@github.com>
wrote:

> This could minimally serve as a building block for the sample operator not
> trying to construct imagestreams and templates until the openshift api
> server is "stable" for the given startup.
>
> I think there's a difference between what that PR does (treat the
> imagestream dockerRepositoryStatus as being "part of the imageregistry - if
> it's not set, the registry isn't available") and adding pre-req conditions
> to the samples operator.
>
> And i'm against adding pre-req conditions... there's going to be an
> expectation that more and more things can attempt to start in parallel and
> should just reconcile.
>
> More fundamentally... is there actually a difference in time between:
>
>    1. create imagestreams while api server is bouncing, they don't get
>    imported until the apiserver stops bouncing
>
> and
>
>    1. wait for the api server to stop bouncing, then create the
>    imagestreams
>
> ?
>
It would have to be prototyped to confirm admittedly.  But fwiw my innate
sense in living this day to day is that the wasted attempts / error cycle
has some impact.

**Comment by gabemontero** [comment]
On Mon, Feb 18, 2019 at 11:59 AM Ben Parees <notifications@github.com>
wrote:

> This could minimally serve as a building block for the sample operator not
> trying to construct imagestreams and templates until the openshift api
> server is "stable" for the given startup.
>
> I think there's a difference between what that PR does (treat the
> imagestream dockerRepositoryStatus as being "part of the imageregistry - if
> it's not set, the registry isn't available") and adding pre-req conditions
> to the samples operator.
>
> And i'm against adding pre-req conditions... there's going to be an
> expectation that more and more things can attempt to start in parallel and
> should just reconcile.
>
> More fundamentally... is there actually a difference in time between:
>
>    1. create imagestreams while api server is bouncing, they don't get
>    imported until the apiserver stops bouncing
>
> and
>
>    1. wait for the api server to stop bouncing, then create the
>    imagestreams
>
> ?
>
> ie are we actually paying any time-cost by creating them while the
> apiserver is "unstable"?
>
> (we're also unlikey to ever be able to establish when the apiserver is
> stable..another operator can come along and introduce a restart at any
> point)
>
> Not sure yet if this is blind luck, or something underneath us has changed
> to mitigate the api server restart.
>
> I believe there were some other fixes that went into the apiserver that
> likely stabilized it a bit.
>
Do you mean the apiserver itself (i.e. openshift/origin) or the apiserver
operator?  Or maybe some combination?
(I'm trying to search now in the interim)

If possible it would be great to explicitly reference those as part of
closing this out.

**Comment by bparees** [comment]
I think it was the api server itself but @deads2k knows for sure.


Ben Parees | OpenShift

**Comment by gabemontero** [comment]
Looking at his test run:  https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/109/pull-ci-openshift-cluster-samples-operator-master-e2e-aws/411/artifacts/e2e-aws/clusteroperators.json

1 minute 30 seconds end to end for samples operator to complete.

Associated pod logs were "clean".

**Comment by gabemontero** [comment]
Even if a recent e2e test run where the install failed to complete, the samples operator completed in less than 2 minutes:  https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/109/pull-ci-openshift-cluster-samples-operator-master-e2e-aws/415/artifacts/e2e-aws/clusteroperators.json

**Comment by bparees** [comment]
@sjenning are you ok w/ closing this?  It seems like the improvements to api server stability have largely resolved the problem.

**Comment by gabemontero** [comment]
Aside from openshift api server churn which appears to have been addressed, which I would still classify as the primary culprit, I did find a bug after repeated repeated runs where if 
a) if our in-payload `jenkins-agent-nodejs` imagestreams was the last imagestream to complete its imports
b) and it did not complete before we got the first event for it
the code would think the `nodejs` was still in progress, and we would not check again until the next relist/resync (so an additional 10 minutes)

So minimally (1 / 64)th chance of that occurring, assuming image importing across the image streams is equitable... maybe less so if you factor in b).

But when I saw it, after several initial runs, I might have seen it like 2 out of 4 times.

PR https://github.com/openshift/cluster-samples-operator/pull/109 addresses this among other things.

So along with the reduction in apiserver restart churn during initial install noted above,  this issue will be marked closed once that PR merges.
